# Generated by Django 6.0 on 2026-01-04 04:25

import django.db.models.deletion
import wallet.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='usdt_balance',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(default=wallet.utils.generate_wallet_address, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
