# Generated by Django 6.0 on 2025-12-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_usdt', models.DecimalField(decimal_places=8, max_digits=20)),
                ('released', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('gift_card_code', models.CharField(blank=True, max_length=255, null=True)),
                ('gift_card_image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('usdt_locked', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('evidence_img', models.ImageField(blank=True, null=True, upload_to='evidence/')),
            ],
        ),
    ]
